<div class="login-wrapper">
		<div class="text-center">
			<h2 class="fadeInUp animation-delay8" style="font-weight:bold">
				<span class="text-success">Garage</span> <span style="color:#ccc; text-shadow:0 1px #fff">Admin</span>
			</h2>
		</div>
		<div class="login-widget animation-delay1">	
			<div class="panel panel-default">
				<div class="panel-heading clearfix">

					<div class="pull-right">
						<span style="font-size:11px;">No tiene ninguna cuenta?</span>
						<a class="btn btn-default btn-xs login-link" href="<?php BASE_URL; ?>index/register" style="margin-top:-2px;"><i class="fa fa-plus-circle"></i> Crear</a>
					</div>
				</div>
				<div class="panel-body">
					<form class="form-login">
						<div class="form-group">
							<label>Usuario</label>
							<input type="text" placeholder="Usuario" class="form-control input-sm bounceIn animation-delay2" >
						</div>
						<div class="form-group">
							<label>Contraseña</label>
							<input type="password" placeholder="Contraseña" class="form-control input-sm bounceIn animation-delay4">
						</div>
		
						<div class="seperator"></div>

						<hr/>
							
						<a class="btn btn-success btn-sm bounceIn animation-delay5 login-link pull-right" href="<?php BASE_URL; ?>inicio"><i class="fa fa-sign-in"></i> Ingresar</a>
					</form>
				</div>
			</div>
		</div>
	</div>


