<h2>Ultimos Post</h2>
<?php if(isset($this->tpersona)&& count($this->tpersona)): ?>
<table>
    <tr>
        <td>ID</td>
        <td>Nombre</td>
        <td>Apellido</td>
        <td>DNI</td>
    </tr>
    <?php for($i = 0; $i<count($this->tpersona);$i++): ?>
    <tr>
        <td><?php echo $this->tpersona[$i]['IdPersona'] ?></td>        
        <td><?php echo $this->tpersona[$i]['Nombre'] ?></td>
        <td><?php echo $this->tpersona[$i]['Apellidos'] ?></td>
        <td><?php echo $this->tpersona[$i]['Dni'] ?></td>
    </tr>
    <?php endfor; ?>
</table>
<?php else:?>
<p><strong>No Hay Persona</strong></p>
<?php endif; ?> 