<div class="login-wrapper">
		<div class="text-center">
			<h2 class="fadeInUp animation-delay10" style="font-weight:bold">
				<span class="text-success">Garage</span> <span style="color:#ccc; text-shadow:0 1px #fff">Admin</span>
			</h2>
	    </div>
		<div class="login-widget animation-delay1">	
			<div class="panel panel-default">
				<div class="panel-heading">
					<i class="fa fa-plus-circle fa-lg"></i> Crear Cuenta
				</div>
				<div class="panel-body">
					<form class="form-login">
						<div class="form-group">
							<label>Usuario</label>
							<input type="text" placeholder="Usuario" class="form-control input-sm bounceIn animation-delay2" >
						</div><!-- /form-group -->
						<div class="form-group">
							<label>Contraseña</label>
							<input type="password" placeholder="Contraseña" class="form-control input-sm bounceIn animation-delay3">
						</div><!-- /form-group -->
						<div class="form-group">
							<label>Confirmar Contraseña</label>
							<input type="text" placeholder="Confirmar contraseña" class="form-control input-sm bounceIn animation-delay4">
						</div><!-- /form-group -->
						<div class="form-group">
							<label>Email</label>
							<input type="text" placeholder="Email" class="form-control input-sm bounceIn animation-delay5">
						</div><!-- /form-group -->

						<div class="seperator"></div>
						<div class="form-group">
							<div class="controls">
								¿Ya tienes una cuenta? <a href="<?php BASE_URL; ?>" class="primary-font login-link">Ingresar</a>
							</div>
						</div><!-- /form-group -->
							
						<hr/>
						<div class="form-group">
							<div class="controls text-right">
								<a class="btn btn-success btn-sm bounceIn animation-delay7 login-link" href="<?php BASE_URL; ?>index/register"><i class="fa fa-plus-circle"></i>Crear</a>
							</div>
						</div><!-- /form-group -->
					</form>
				</div>
			</div><!-- /panel -->
		</div><!-- /login-widget -->
	</div>
